name: Random-Proj
version: @version@
description: A Random-Project
main: net.apherfox.random-proj.Random-Proj

commands:
  hello:
    description: say hello to the user
  tp:
    description: teleport to the spawn