name: Random-Proj
version: 0.1
main: net.apherfox.random-proj.Random-Proj

author: ApherFox
description: This is just an attempt for me to create something 
website: http://fluffpalace.ga/

commands:
  rpj:
    description: Core command for Random-Proj
    aliases: [rpj]
